/**
 * This file implements a catch-all route that renders the user-facing pages
 * generated by Puck. For any route visited (with exception of other hardcoded
 * pages in /app), it will check your database (via `getPage`) for a Puck page
 * and render it using <Render>.
 *
 * All routes produced by this page are statically rendered using incremental
 * static site generation. After the first visit, the page will be cached as
 * a static file. Subsequent visits will receive the cache. Publishing a page
 * will invalidate the cache as the page is written in /api/puck/route.ts
 */

import { PuckPreview } from './ui/components/puck-preview';
import { notFound } from 'next/navigation';
import { Metadata } from 'next';
import { getPage } from '@/lib/get-page';
import { BackToDashboardButton } from './ui/components/BackToDashboardButton';
import { EditButton } from './ui/components/EditButton';
import { ExportPDFButton } from './ui/components/ExportPDFButton';

export async function generateMetadata({
  params,
}: {
  params: Promise<{ puckPath: string[] }>;
}): Promise<Metadata> {
  const { puckPath = [] } = await params;
  const path = `/${puckPath.join('/')}`;

  return {
    title: getPage(path)?.root.props?.title,
  };
}

export default async function Page({
  params,
}: {
  params: Promise<{ puckPath: string[] }>;
}) {
  const { puckPath = [] } = await params;
  const path = `/procs/${puckPath.join('/')}`;
  console.log('path is ', path);
  const data = getPage(path);
  console.log('data is ', data);

  if (!data) {
    return notFound();
  }

  const formatTimestamp = (isoString: string) => {
    if (!isoString) return '';
    const date = new Date(isoString);
    const options = {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: 'numeric',
      minute: 'numeric',
      timeZoneName: 'short',
    };
    // `toLocaleString` formats the date based on the user's browser settings
    return date.toLocaleString(undefined, options);
  };

  return (
    <div className="p-4 bg-white mx-auto max-w-screen">
      <div className="flex">
        <BackToDashboardButton />
        <div className="flex flex-col ml-4 mt-2 align-middle">
          <span className="text-xs text-gray-400">
            Created By: {data.metadata.createdBy}
          </span>
          <span className="text-xs text-gray-400">
            Last Updated: {formatTimestamp(data.metadata.updatedAt)}
          </span>
        </div>
        <div className="ml-auto flex gap-4 items-center">
          <div>
            <ExportPDFButton />
            <EditButton path={path} />
          </div>
        </div>
      </div>

      {/* Paper render */}
      {/* <div className="min-h-screen px-16 py-24 mt-24 mb-32 mx-32 bg-white border border-gray-100 shadow-md"> */}
      <PuckPreview data={data} />
      {/* </div> */}
    </div>
  );
}

// Force Next.js to produce static pages: https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#dynamic
// Delete this if you need dynamic rendering, such as access to headers or cookies
export const dynamic = 'force-static';
